-- Migration: Create licenses table for standalone license keys
-- Date: 2026-01-11
-- Description: Store standalone license keys for desktop app purchases

-- ============================================================================
-- LICENSES TABLE
-- ============================================================================
-- Stores license keys for standalone (non-subscription) purchases

CREATE TABLE IF NOT EXISTS licenses (
  id TEXT PRIMARY KEY, -- lic_xxx format from generate-license function

  -- Customer info
  customer_id TEXT NOT NULL, -- Clerk user ID or Stripe customer ID
  customer_email TEXT NOT NULL,
  customer_name TEXT,

  -- Organization (for team licenses)
  organization_id UUID REFERENCES organizations(id) ON DELETE SET NULL,

  -- License details
  product TEXT NOT NULL CHECK (product IN ('craft', 'artist', 'suite')),
  tier TEXT NOT NULL DEFAULT 'standard' CHECK (tier IN ('standard', 'pro', 'lifetime')),
  seat_count INTEGER NOT NULL DEFAULT 1 CHECK (seat_count >= 1),

  -- Validity
  issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ, -- NULL for lifetime licenses
  revoked_at TIMESTAMPTZ, -- Set when license is revoked (refund, etc.)

  -- Payment tracking
  stripe_payment_id TEXT,

  -- Additional data (features, etc.)
  metadata JSONB DEFAULT '{}'::jsonb,

  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for fast lookups
CREATE INDEX idx_licenses_customer_id ON licenses(customer_id);
CREATE INDEX idx_licenses_customer_email ON licenses(customer_email);
CREATE INDEX idx_licenses_organization_id ON licenses(organization_id);
CREATE INDEX idx_licenses_product ON licenses(product);
CREATE INDEX idx_licenses_tier ON licenses(tier);
CREATE INDEX idx_licenses_expires_at ON licenses(expires_at);
CREATE INDEX idx_licenses_stripe_payment_id ON licenses(stripe_payment_id);

-- Enable Row Level Security
ALTER TABLE licenses ENABLE ROW LEVEL SECURITY;

-- Policy: service role only (accessed via Edge Functions)
CREATE POLICY "Service role access for licenses" ON licenses
  FOR ALL USING (auth.role() = 'service_role');

-- Auto-update updated_at trigger (reuses function from subscriptions migration)
CREATE TRIGGER update_licenses_updated_at
  BEFORE UPDATE ON licenses
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================================================

COMMENT ON TABLE licenses IS 'Standalone license keys for desktop app purchases (ESCAPECRAFT, ESCAPEARTIST, Suite)';
COMMENT ON COLUMN licenses.id IS 'License ID in lic_xxx format, generated by generate-license function';
COMMENT ON COLUMN licenses.customer_id IS 'Clerk user ID for logged-in users, or Stripe customer ID for guest purchases';
COMMENT ON COLUMN licenses.product IS 'craft = ESCAPECRAFT, artist = ESCAPEARTIST, suite = both apps';
COMMENT ON COLUMN licenses.tier IS 'standard = 1yr updates, pro = 2yr updates, lifetime = perpetual updates';
COMMENT ON COLUMN licenses.seat_count IS 'Number of machines/users this license covers';
COMMENT ON COLUMN licenses.expires_at IS 'When the license expires (NULL for lifetime licenses)';
COMMENT ON COLUMN licenses.revoked_at IS 'Set when license is revoked (e.g., after refund)';
COMMENT ON COLUMN licenses.metadata IS 'JSON containing features array and other license data';
