-- Re-drop licenses.organization_id, reverting a transient emergency band-aid.
--
-- Timeline:
--   1. 20260531_01_teardown_seat_org_backend dropped licenses.organization_id
--      (the seat-based teams/org model was retired).
--   2. The still-deployed generate-license function was *inserting*
--      organization_id, so minting immediately broke ("Failed to store license").
--      As an emergency fix the column was re-added out-of-band via the MCP
--      migration `readd_licenses_organization_id_unbreak_mint`.
--   3. generate-license / get-license-key / get-licensed-download / webhook have
--      now been cleaned of every organization_id reference (dead audit/org
--      branches removed) and generate-license has been redeployed, so the column
--      is once again unused (0 rows ever populated it).
--
-- This re-drops it for good. Idempotent: a fresh replay from the teardown
-- migration never re-adds the column, so `if exists` makes this a safe no-op.
alter table public.licenses drop column if exists organization_id;
